-- https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, UI.GENDER, COUNT(OS.USER_ID) USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER ASC
