-- https://school.programmers.co.kr/learn/courses/30/lessons/157342

SELECT CAR_ID, DATEDIFF(DAY,START_DATE,END_DATE)/COUNT(CAR_ID) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE SUM(DATEDIFF(DAY,START_DATE,END_DATE))/COUNT(CAR_ID)>6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC