-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY J
ON F.SHIPMENT_ID=J.SHIPMENT_ID
GROUP BY F.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) DESC
LIMIT 3