-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY J
ON J.FLAVOR=F.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER+J.TOTAL_ORDER) DESC
LIMIT 3